name: SecretsTest

on: [push, pull_request]

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: List environment
        run: export
      - name: echo secret1
        run: echo ${{ secrets.ftppassword}}
      - name: run ftp 
        run: bash ftp.sh server 21 ${{ secrets.ftppassword}}
